### ISSUE TITLE
Mabye some sort of security?

### ISSUE THREAD

**Issue by illemonati** [SheepTester/fun-gunn-run#5]
Right now you can do whatever you want with the leaderboard.
Can u at least make it harder?
_________________________________

P.S.
also, it doesn't seem like too many people played this. I am quite surprised. Mostly probably played in school, but still!
Only 21 ips
WoW

**Comment by SheepTester** [comment]
I don't think it's possible without keeping track of keypresses and running through them on the server side to see if they make sense

**Comment by SheepTester** [comment]
ok
